### ISSUE TITLE
Option for include parsed 0 values

### ISSUE THREAD

**Issue by MartinNovak83** [marioizquierdo/jquery.serializeJSON#101]
First of all, thank you for your great plugin. 

I have only one issue - with parseNumbers: true, elements with value="0" are ignored, because are treated like falsy. This is somethink I don't want. For some reason I need elements with 0 in json result. So there should be some option to achieve this. Or did I overlook some existing settings? I tried to play with skipFalsy... options but without success.

**Comment by marioizquierdo** [comment]
Maybe you are using a checkbox? Checkboxes in HTML forms are ignored if they are unchecked. If this is the case for you, try setting the attribute `data-unchecked-value="0"` (or the JS option `checkboxUncheckedValue: 0`).

See more details on the README section for unchecked checkboxes: https://github.com/marioizquierdo/jquery.serializeJSON#include-unchecked-checkboxes
