### ISSUE TITLE
Raise  ERROR: Invalid type in value

### ISSUE THREAD

**Issue by devbtc** [marioizquierdo/jquery.serializeJSON#103]
serializeJSON raise error when i supplied following string in value 
```
  Estes Express Lines (Guaranteed LTL Standard Transit: 10AM)
 ```
![image](https://user-images.githubusercontent.com/66318449/87631426-e4eae100-c754-11ea-953a-96323fd0a610.png)

**Comment by marioizquierdo** [comment]
That seems to be the `name`, not the `value`. Field names can not have colons, or the serializeJSON parser will think that everything after the colon is the type (string, number, etc.).

Are you sure you are using the right attributes in your form: `<input name="key" value="value>"` ?

**Comment by devbtc** [comment]
Removed  **:**(colon) from `name` attribute. now it works. 
thanks. @marioizquierdo

**Comment by AndrewSouthpaw** [comment]
I'm curious why that isn't considered a bug? It's my understanding that a form can have fields with a `name` that includes a colon, as far as the HTML spec is concerned.

We're bumping into this issue right now, and before I just strip out all the colons I wonder if there's room to change the parsing logic instead?

**Comment by marioizquierdo** [comment]
Yes, a form can have fields with a `name` that includes a colon, and brackets, and most ascii characters. However, this plugin is designed to interpret the field names and decide how to serialize the values from those names. The syntax is non-negotiable, but there are plenty of options for customization. I'm thinking about improving the `:type` syntax to allow names with colons and maybe also an option to ignore types on field names: https://github.com/marioizquierdo/jquery.serializeJSON/pull/102

**Comment by marioizquierdo** [comment]
Fixed on PR 105.

You can now use the option `{disableSemicolonTypes: true}`
