### ISSUE TITLE
Mixup between colon and semicolon

### ISSUE THREAD

**Issue by andrews05** [marioizquierdo/jquery.serializeJSON#106]
There's a lot of references to semicolons in the docs, as well as the "disableSemicolonTypes" option. Just thought I'd point out that ":" is _colon_. A _semicolon_ is ";".

**Comment by marioizquierdo** [comment]
Oops 😅 
I'll do a quick search in the project to make sure it uses the proper naming in the docs. I'll also rename the option `disableSemicolonTypes` to `disableColonTypes `, it was added a week ago and I think I'm in time to react before too many people depend on it.
Thanks!

**Comment by marioizquierdo** [comment]
Problem solved https://github.com/marioizquierdo/jquery.serializeJSON/commit/22d36a8103ab032f6c9f70ae3580c88c847ffc40
Thanks!
