### ISSUE TITLE
Versioning scheme?

### ISSUE THREAD

**Issue by DavidAnderson684** [marioizquierdo/jquery.serializeJSON#117]
Hi, please can you clarify what versioning scheme this project is using? It's unclear whether we can rely on semantic versioning conventions when specifying a version to use, or not.

Also - the readme mentions 3.2.0, but this doesn't exist at https://github.com/marioizquierdo/jquery.serializeJSON/releases (where does https://www.npmjs.com/package/jquery-serializejson pick it up from??).

**Comment by marioizquierdo** [comment]
Yes, I use semantic versioning: `<major>.<minor>.<bugfix>`. Minor and bugfix releases don't introduce breaking changes.

Thanks for finding the version inconsistency. I didn't do the last release properly, it was pushed to npm but didn't make a Github tag/release. I just released `3.2.1` with a new tag, and to npm. Thank you!
