### ISSUE TITLE
Initialize form values from object

### ISSUE THREAD

**Issue by KES777** [marioizquierdo/jquery.serializeJSON#125]
It would be nice to do vice versa: from given hash setup form values

```javascript
$("form").setData({foo: {bar: "a", bof: "b"}, hello: "world"});
```

which in turn will fill corresponding form fields with given values:

```html
<input name="foo[bar]" value="a">
<input name="foo[bof]" value="b">
<input name="hello" value="world">
```

**Comment by marioizquierdo** [comment]
It is out of scope for this plugin. But yes that would be nice, and if someone builds it I would be happy to make a reference on the README file here :)

**Comment by KES777** [comment]
Found this plugin which can do that: https://github.com/brainfoolong/form-data-json

**Comment by wshiadai** [comment]
hope support this feature
