### ISSUE TITLE
Ignoring empty form fields

### ISSUE THREAD

**Issue by ruiquelhas** [marioizquierdo/jquery.serializeJSON#28]
As far as I could understand, there is no way to ignore empty form fields, excluding them from the resulting object. If so, is this feature on the roadmap or are you open to a pull request?

**Comment by danielkummer** [comment]
@marioizquierdo solution doesn't work for me if I'm using array elements, but I found this solution quite satisfying:

`````
obj = $form.find(':input').filter(function () {
                    return $.trim(this.value).length > 0
                }).serializeJSON();
````

**Comment by brock** [comment]
@marioizquierdo :+1:
