### ISSUE TITLE
Serialize select with multiple attribute

### ISSUE THREAD

**Issue by VeXell** [marioizquierdo/jquery.serializeJSON#31]
I try to serialize form with select with multiple attribute and i got only one value from this field.

For example http://jsfiddle.net/0sn3ppof/1/

Json object is {"name":"text","values":"3"}
But $('select').val() is ["1","3"]

thx u for your plugin.

**Comment by marioizquierdo** [comment]
Since you want "values" to be an array, you should use name="values[]".

For example: http://jsfiddle.net/0sn3ppof/2/

```html
<form id="my-form">
    <input type="text" name="name" value="text" /><br/>
    <select name="values[]" multiple>
        <option value="1" selected>Moscow</option>
        <option value="2">Paris</option>
        <option value="3" selected>London</option>
    </select>    
</form>
```
