### ISSUE TITLE
Empty multiple select

### ISSUE THREAD

**Issue by voidpp** [marioizquierdo/jquery.serializeJSON#37]
So I have a select sg like this:
```html
<select name="camel[]" multiple>
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
</select>
```
When I try to serialize with `serializeJSON` and no one option is selected, the `camel` array is missing from the result, but I check any of the options, the `camel` array is appearing in the result.

Can I miss something? I searched, but I not found any options for `serializeJSON` to give me back the empty `camel` array.
Or if this is not possible at this time could implement this feature?

I temporary bypass the problem with a hidden input, but I really don't like this solution.

**Comment by marioizquierdo** [comment]
That's just how is specified by the standard W3C rules for successful controls: if it's not selected, then it's not included in the request.

But obviously you want an empty array if nothing is selected.
It seems to be the same confusing problem as with the unchecked checkboxes.

Maybe I should add yet another option to serializeJSON like `{ensureEmptyListForSelectMultiple: true}`... but I don't see how to "easily" solve this problem.

For now, the hidden input will solve it:

```html
<input type="hidden" name="camel:array" value="[]"/> <!-- ensure empty array -->
<select name="camel[]" multiple>
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
</select>
```
