### ISSUE TITLE
2.6.0 release?

### ISSUE THREAD

**Issue by mHubbell** [marioizquierdo/jquery.serializeJSON#42]
Hiya, (first off thanks for the very handy plugin) I could really use the new "customTypes" option but it seems the 2.6.0 version has not been tagged yet so I cant pull it via bower (properly)  unless i go to the latest commit. Would very much appreciate a new tag. Cheers!

**Comment by marioizquierdo** [comment]
Ups, sorry for that.
Sure thing, I'll create the tag asap.

**Comment by mHubbell** [comment]
Thanks much!
