### ISSUE TITLE
Array of Objects with dot (.) syntax

### ISSUE THREAD

**Issue by zxcnasab** [marioizquierdo/jquery.serializeJSON#47]
Hi,

I'm currently using this stuff to populate array of objects. This is on ASP.NET MVC
http://ivanz.com/2011/06/16/editing-variable-length-reorderable-collections-in-asp-net-mvc-part-1/.

What it does is something like this :

```
<ul>
<li>
<input name="Ingredients.Index" type="hidden" value="425b56ca-5c9c-4d49-b30b-346b6d0bff6f">
<input name="Ingredients[425b56ca-5c9c-4d49-b30b-346b6d0bff6f].IngredientSubTitle" type="text" value="">
<input name="Ingredients[425b56ca-5c9c-4d49-b30b-346b6d0bff6f].IngredientName" type="text" value="cauliflower">
</li>


<li style="padding-bottom:15px">

<input name="Ingredients.Index" type="hidden" value="d5422e9d-7cec-4b01-9378-d71f2ea9b188">
<input name="Ingredients[d5422e9d-7cec-4b01-9378-d71f2ea9b188].IngredientSubTitle" type="text" value="">
<input name="Ingredients[d5422e9d-7cec-4b01-9378-d71f2ea9b188].IngredientName" type="text" value="apples">
</li>


<li>
<input autocomplete="off" name="Ingredients.Index" type="hidden" value="5f9dda33-4be4-4f21-a249-3c291af03153">
<input name="Ingredients[5f9dda33-4be4-4f21-a249-3c291af03153].IngredientSubTitle" type="text" value="">
<input name="Ingredients[5f9dda33-4be4-4f21-a249-3c291af03153].IngredientName" type="text" value="red onion">

</li>
</ul>
```
Basically, it is indexing an array with the use of GUID instead of int.

I've used useIntKeysAsArrayIndex:true but what it does is it is only removing the label in front of the GUID.

What I would like to achieve is some thing like this :

```
"Ingredients": [
         { "IngredientSubtitle": "", "IngredientName": "cauliflower" },
         { "IngredientSubtitle": "", "IngredientName": "apples" },
         { "IngredientSubtitle": "", "IngredientName": "red onion" },
]
```

Thanks

**Comment by marioizquierdo** [comment]
Seems like you want an array of objects, but you can not create an array with non-integer indexes in JavaScript or JSON. If it's an array, it must be indexed from 0 to N-1, otherwise just use an object indexed by the uuid.

If what you want is a simple array o objects, then just use integer indexes:

```
<ul>
<li>
<input name="Ingredients[0][IngredientSubTitle]" type="text" value="">
<input name="Ingredients[0][IngredientName]" type="text" value="cauliflower">
</li>

<li>
<input name="Ingredients[1][IngredientSubTitle]" type="text" value="">
<input name="Ingredients[1][IngredientName]" type="text" value="apples">
</li>

<li>
<input name="Ingredients[2][IngredientSubTitle]" type="text" value="">
<input name="Ingredients[2][IngredientName]" type="text" value="red onion">
</li>
</ul>
```

Then you can use the option `useIntKeysAsArrayIndex:true` to make sure it generates an array (instead of an object with int-like string keys).

Unfortunately `serializeJSON` is opinionated about how to organize the input names, and doesn't work with other formats.

**Comment by zxcnasab** [comment]
Yeah, seems like there's no other way around it. Perhaps ill just create an additional function for this case.
