### ISSUE TITLE
Support parse comma separated value as Array.

### ISSUE THREAD

**Issue by hackwaly** [marioizquierdo/jquery.serializeJSON#53]
Consider some HTML select tag replacement (such as dropdown component of semantic-ui) allow multiple selection. And it will write multiple selection as comma separated string to a hidden field's value property.

**Comment by marioizquierdo** [comment]
I'm not sure I understand what you say, but I assume you mean something like having a hidden input value like "1,2,3,4", and you want to have some way to tell serializeJSON to parse that as an array ...

This is what would happen with all the default settings:

```html
<input type="hidden" name="mylist" value="1,2,3,4"/>
```
```javascript
$('input').serializeJSON();
//=> {"mylist": "1,2,3,4"}
```
It is parsed as a String, and this is how it should work out of the box,

However, parsing comma separated with with types is very simple.

One option that "almost works" is using the type `:array`, that works if you use brackets like "[1,2,3,4]":

```html
<input type="hidden" name="mylist:array" value="[1,2,3,4]"/>
```
```javascript
$('input').serializeJSON();
//=> {"mylist": [1,2,3,4]}
```

Or, you can make your own type to support the "1,2,3,4" value (with no brackets). Let's call this type `commaSeparated`:

```html
<input type="hidden" name="mylist:commaSeparated" value="1,2,3,4"/>
```
```javascript
$('input').serializeJSON({
  customTypes: {
    commaSeparated: function(str) {
      return str.split(',');
    },
});
//=> {"mylist": ["1", "2" , "3", "4"]}
```

Of course, your `commaSeparated` parser could do more things like converting the array elements to integers, or making sure to trim the elements.

**Comment by hackwaly** [comment]
Thanks! This actually solve my problem.
