### ISSUE TITLE
Values with quotes

### ISSUE THREAD

**Issue by kubamn** [marioizquierdo/jquery.serializeJSON#56]
Hi,

Is this a bug of the plugin that it can't handle double quotes in strings? 

It doesn't escape them at all, when I'm trying to JSON a form with tinyMCE inside it. In the textarea from tinyMCE I have images with attibutes like class="" etc.

Is there any way I could escape the double quotes?

**Comment by marioizquierdo** [comment]
I'm not understanding the question. Can you provide an example?
What is the value in the textarea (you can check with plain jQuery like `$("textarea").val()`)?

**Comment by marioizquierdo** [comment]
@kubamn if you don't mind, I will close this issue as it is not clear and could not handle
