### ISSUE TITLE
serializeArray in IE on non form element

### ISSUE THREAD

**Issue by anikitas** [marioizquierdo/jquery.serializeJSON#58]
Hello,

I discovered that in in IE11 and probably Edge using a serializeArray will not get the data if the selector is not a form.

I made a simple test changing from:
**formAsArray = $form.serializeArray();**
To
**formAsArray = $form.find(':input').serializeArray();**

and it seems to work also on IE.

Is this a valid approach or it might have any side effects.

I'm actually trying to serialize a div element.
Maybe i should call serializeJSON with this find instead?
e.g: $('#myDiv').find(':input').serializeJSON();

Any suggestions would help.

Thanks in advance!

**Comment by marioizquierdo** [comment]
`serializeJSON` relies on the jQuery `serializeArray` method, if `serializeArray` has a bug, then `serializeJSON` has a bug.

But I am confident that jQuery will fix that bug faster than I could do myself. My guess is that you are probably not using the last version of jQuery, which probably has that problem with IE11 fixed.

In any case, serializeArray is described like this in the jQuery documentation: `It operates on a jQuery collection of forms and/or form controls.`, so I guess technically a `div` is not a valid collection.

If your `$form` is actually a `$div`, then I would suggest just do it like this:

```javascript
$div.find(':input').serializeJSON();
```

**Comment by anikitas** [comment]
Hello,
Thanks for the reply.

I think this is a very old Ticket: https://dev.jquery.com/ticket/8883
Strangely it works on other browsers even without form element.
Only in IE it returns an empty array []

I tested this approach: $div.find(':input').serializeJSON();
This approach works fine in all browsers in non form elements like div or fieldset.

I just wondered if you where aware of the issue with IE11, or if you have some other alternative.

Thanks again, really good work!

**Comment by marioizquierdo** [comment]
Maybe only IE is right, and everybody else is wrong lol

**Comment by Desertsnowman** [comment]
@anikitas if your form is not too large or you not too worried about some performance hits, you can always do
``` js
var object = $('<form>').append( $('#myForm').clone() ).serializeJSON();
```
Which solved my problems.
