### ISSUE TITLE
Can I serialize radio input types?

### ISSUE THREAD

**Issue by kevinisaac** [marioizquierdo/jquery.serializeJSON#59]
From the readme file, there is no mention of radio input types and it doesn't work either. Will be nice if the functionality is added too, or is there any reason why it isn't added?

**Comment by marioizquierdo** [comment]
@kevinisaac that's true, there's no direct mention to radio inputs in the README file, but they should definitely work, just like any other input. Just make sure they are valid which means that the included elements **cannot be disabled and must contain a name attribute**.

Here is an example:

```
<form>
    <input type="radio" name="myopt" value="1" checked> Opt1 <br>
    <input type="radio" name="myopt" value="2"> Opt2 <br>
    <input type="radio" name="myopt" value="3"> Opt3
</form>
```

```javascript
$("form").serializeJson();
// returns => { "myopt": "1" }
```

**Comment by kevinisaac** [comment]
@marioizquierdo I don't know what went wrong but, right after posting this issue it worked for me. I probably missed the value attribute the first time, or I forgot to restart the server. 

Thanks for your reply! :)

**Comment by danieldunderfelt** [comment]
Hi!

I'd also need the radio fields to be included in the serialized form when I supply the `checkboxUncheckedValue` setting. Now they are not if all radio buttons in the group are unchecked, which is the initial state in my case. I'll probably figure out something else for now as I'm on a deadline, but just know that this is a valid use case.

**Comment by marioizquierdo** [comment]
@danieldunderfelt Yes the `checkboxUncheckedValue` works for checkboxes only, not radio buttons.

If you can edit your HTML, you can have a "default value" for when no radio is selected by adding a `hidden` field before the radio buttons with the same `name`. For example:
```html
<form>
  <input type="hidden" name="myopt" value="0">
  <input type="radio"  name="myopt" value="1"> Opt1 <br>
  <input type="radio"  name="myopt" value="2"> Opt2 <br>
</form>
```

```js
$("form").serializeJson();
// returns => 
{ "myopt": "0" }
```
