### ISSUE TITLE
Multiple select with default property

### ISSUE THREAD

**Issue by scorpy1975** [marioizquierdo/jquery.serializeJSON#61]
Hi,

thanks for plugin, helped me alot.

I have 2 select multiple, is it posibble to serialize it with default property value for each one
 
```
  <select name="users[][id]" data-typeid="1" multiple>
        <option value="1">a</option>
        <option value="2" selected>b</option>
        <option value="3" selected>c</option>
    </select>
    

    <select name="users[][id]" data-typeid="2" multiple>
        <option value="4">d</option>
        <option value="5" selected>e</option>
        <option value="6" selected>f</option>
    </select>
```

expected result

`{"users":[{"id":"2","typeid":"1"},{"id":"3","typeid":"1"},{"id":"5","typeid":"2"},{"id":"6","typeid":"2"}]}`

**Comment by marioizquierdo** [comment]
I don't think you can do a select multiple which elements are also objects out of the box.

You could achieve that using a type like `:object` and make the values be json objects:

```
<select name="users[]:object" data-typeid="1" multiple>
    <option value="{'id': '1', 'typeid': '1'}">a</option>
    <option value="{'id': '2', 'typeid': '1'}" selected>b</option>
    <option value="{'id': '3', 'typeid': '1'}" selected>c</option>
</select>
```

Or make your own custom type (i.e. `name="users[]:typeid1"`) that converts the number into the object you want with the typeid: 1 property.

Or just use a different serialized output that naturally fits the naming scheme. For example:

```
<select name="user_ids[typeid_1][]" data-typeid="1" multiple>
    <option value="1">a</option>
    <option value="2" selected>b</option>
    <option value="3" selected>c</option>
</select>

<select name="user_ids[typeid_2][]" data-typeid="2" multiple>
    <option value="4">d</option>
    <option value="5" selected>e</option>
    <option value="6" selected>f</option>
</select>
```

result:

```
{"user_ids": {
  "typeid_1": ["2", "3"],
  "typeid_2": ["5", "6"],
}}
```

Then you can convert that output to your desired result.

**Comment by scorpy1975** [comment]
thanks for reply,

 

I did similar thing in the end

 

<option value="1:1">a</option>

<option value="2:1">b</option>

 

<select name="users[]:management" multiple>

<option value="1:1">a</option>

<option value="2:1">b</option>

<option value="3:1">c</option>

 

</select>

 

customTypes: {

            management: function (str) { 

                var arr = str.split(":");

                return { "UsersID" : arr[0], "UsersTypeID" : arr[1]};

             }

}

 

 

end result

 

"users":[{"UsersID":"1","UsersTypeID":"1"},{"UsersID":"2","UsersTypeID":"1"},{"UsersID":"3","UsersTypeID":"1"}]

 

 

Krunoslav Pongrac

-------------------

Globaldizajn d.o.o.

Bani 75

10000 Zagreb

Tel. 01/2222-802, 01/2222-800

Fax. 01/2222-806

www.globaldizajn.hr

krunoslav.pongrac@globaldizajn.hr

**Comment by marioizquierdo** [comment]
That's an excellent use of the customTypes feature.
