### ISSUE TITLE
Is there a demo? How to output the results?

### ISSUE THREAD

**Issue by onigetoc** [marioizquierdo/jquery.serializeJSON#62]
Is there a demo? How to output the results?
I want to output the result to a "pre" to see the result.

I want also create a addon to this plugin to convert json to css markup.

Update: Hi, i finally did a basic working demo on jsfiddle.
http://jsfiddle.net/onigetoc/azoxeLLv/2/

**Comment by onigetoc** [comment]
Hi, i finally did a basic demo on jsfiddle
[http://jsfiddle.net/onigetoc/azoxeLLv/2/](url)

**Comment by onigetoc** [comment]
I did a Form to CSS.
i'm looking to find a mart way to add px, % and css3 suffix to it to create a CSS generator.
https://jsfiddle.net/onigetoc/qhatbqr7/8/

**Comment by marioizquierdo** [comment]
There was no fiddle, thanks for making one. The code can also be easily tested just by running the jasmine tests (open the test html file in a browser) and just add new tests as you need, but I agree the fiddle is more convenient for some cases.

With the css3 prefixes, I would be careful or you may find yourself reimplementing sass functions in the formToCSS project. But maybe you can solve it with some manual post-processing of the output.

**Comment by onigetoc** [comment]
Hi, What do you mean by? "or you may find yourself reimplementing sass functions in the formToCSS project"

Here a more advanced not final version based on serializeJSON.
https://rawgit.com/onigetoc/FormToCSS/master/example/demo.html

With this, i'm building my own CSS generator 10X faster than usual.
