### ISSUE TITLE
Is there a way to ignore empty input?

### ISSUE THREAD

**Issue by onigetoc** [marioizquierdo/jquery.serializeJSON#64]
Is there a way to ignore empty input?
I mean ignore the empty text input like de :skip do

By the way, I just create a plugin who use your SerializeJSON.
It convert form to css.
https://rawgit.com/onigetoc/FormToCSS/master/example/demo.html

**Comment by marioizquierdo** [comment]
Just filter out the jQuery selector before calling serializeJSON on the matched elements, i.e. `$(input).not('.ignoreme').serializeJson()`

Or use the `:skip` type.
