### ISSUE TITLE
checkbox value is fail!

### ISSUE THREAD

**Issue by qq362220083** [marioizquierdo/jquery.serializeJSON#66]
html:
`<input type="checkbox" name="test" value="1" checked="checked" />
<input type="checkbox" name="test" value="2" checked="checked" />
<input type="checkbox" name="test" value="3" checked="checked" />`

jquery.serializeJson result:
`{test:3}`

desired result:
`{test:[1,2,3]}`

**Comment by marioizquierdo** [comment]
The issue is on the "name" attribute. If you name all the inputs with the same name, only the last value will be used. That's why in `serializeJSON` you can name attributes to be an array.

Simply use `name="test[]"`.
