### ISSUE TITLE
Checkbox list

### ISSUE THREAD

**Issue by John-gecko** [marioizquierdo/jquery.serializeJSON#76]
I have the following within a form

```
<div class="multiplechoice form-group">
	<label for="checkboxlist1" class="fieldLabel">label text</label>
    <span class="checkboxlist" id="checkboxlist1">
		<input type="checkbox" name="checkboxlist1" id="checkboxlist1_0" value="value 1" /> 
		<label for="checkboxlist1_0">value 1</label><br />


		<input type="checkbox" name="checkboxlist1" id="checkboxlist1_1" value="value 2" /> 
		<label for="checkboxlist1_0">value 1</label><br />


		<input type="checkbox" name="checkboxlist1" id="checkboxlist1_2" value="value 3" /> 
		<label for="checkboxlist1_0">value 1</label><br />
	  
	</span>
</div>
```

as its a checkbox list the names are all the same but the serializeJSON only stores the last selected value

how would you cope with this situation - a custom function?

Cheers
J

**Comment by marioizquierdo** [comment]
Just name the inputs with an ending `[]`:
```html
<input type="checkbox" name="checkboxlist1[]" value="value 1" />
<input type="checkbox" name="checkboxlist1[]" value="value 2" />
<input type="checkbox" name="checkboxlist1[]" value="value 3" />
```

That's the way to tell the serializer that the values should be added to the list, not replaced with the last value.

**Comment by John-gecko** [comment]
Hi
Yeah I was aware of that one but cannot change the names as the cms relies on the existing names.
I have been able to add the"[]" via js before sending it to serializeJSON

Thanks for all your great work on this
Cheers
J

**Comment by marioizquierdo** [comment]
Oh I see. Yeah this plugin is designed to work with input names.

If you can not change them and you don't need nested values, you may be better off directly using jQuery [.serializeArray()](https://api.jquery.com/serializeArray/).
