### ISSUE TITLE
Serialize every type of element

### ISSUE THREAD

**Issue by L4KEofFIRE** [marioizquierdo/jquery.serializeJSON#79]
At the moment you can only serialize `<form>`-tags, but if you change line
31 `formAsArray = $form.serializeArray();`
to
`formAsArray = $form.find(':input,select,textarea,keygen').not(':disabled').serializeArray();`
the plugin will be much more mighty and you can serialize every type of element.

**Comment by marioizquierdo** [comment]
An issue created by a troll? I should close it immediately!

BTW, `serializeJSON` already works on other elements, in fact it works on the same elements as (jQuery serializeArray)[https://api.jquery.com/serializeArray/], for example you can call it on a set of inputs or textareas. No need to explicitly do a `.find()` operation.

It may be different for Zepto or other library that mimics the jQuery interface, but I'm not going to change the architecture of the plugin to support those.
