### ISSUE TITLE
Nested array within an Array Object

### ISSUE THREAD

**Issue by randallmlough** [marioizquierdo/jquery.serializeJSON#88]
I was hoping to figure out how I can have an array or an array object within another array object.

my desired output
```
{
  "staff": [{
    "name": "john doe",
    "another_array": [
        "something",
        "something2"
    ],
    "array_obj": [{
         "title": "something",
         "desc": "foobar"
    }]
  }]
}
```
I've tried something like
```
<input name="staff[]another_array[]">
```
and something like...
```
<input name="staff[]array_obj[][title]">
```
But none of the above works. It doesnt appear you can have nested arrays. Is this true?

**Comment by cappuccinoqi** [comment]
There are something wrong in your code : `<input name="staff[]another_array[]">`  ,to achieve your ideal result, it should be like this:`<input name="staff[another_array][]">` . You'd better take a look at the README.md .The full code is here : 
    <input type="text" name="staff"              value="" />

    
    <input type="text" name="staff[name]"         value="john doe" />
    <input type="text" name="staff[another_array][]"  value="something" />
    <input type="text" name="staff[another_array][]"  value="something2" />

    
    <input type="text" name="staff[array_obj][title]"             value="something" />
    <input type="text" name="staff[array_obj][desc]"             value="foobar" />

**Comment by randallmlough** [comment]
Thanks for the quick reply @cappuccinoqi! Your suggestion wasn't the exact output I was looking for, but tinkering with it some more based on your guidance I got it work using the following structure

```
       <input type="text" name="staff[][simpleArray][]" value="person 1 - simple array 1">
        <input type="text" name="staff[][arrayObj][][title]" value="person 1 - Array obj title 1">
```
That results in
```
"staff": [{
        "item": "person 1 - item",
        "simpleArray": ["person 1 - simple array 1", "person 1 - simple array 2"],
        "arrayObj": [{
            "title": "person 1 - Array obj title 1",
            "desc": "person 1 - Array obj description 1"
        }]
    }]
```

**Comment by cappuccinoqi** [comment]
aha , I did this in a hurry, perhaps it was because Chrome Debug Mode doesn't show the result well.Good to hear that my suggestion is useful.

**Comment by cappuccinoqi** [comment]
@randallmlough If you don't mind ,would you like to tell me how can you get that result ? My output in Chrome is not tidy as your result.

**Comment by marioizquierdo** [comment]
Using the `array[][nestedObjKey][]` syntax works, but it will add keys to the object only if the key does not exist, and create new object elements if the key does not exist... Kind of magic behavior that may work great or be super-confusing. To avoid confusion, I recommend using the array indexes and the option `useIntKeysAsArrayIndex: true`:

```html
<input type="text" name="staff[0][name] value="john doe">
<input type="text" name="staff[0][another_array][0]" value="something">
<input type="text" name="staff[0][another_array][1]" value="something2">
<input type="text" name="staff[0][array_obj][0][title]" value="something">
<input type="text" name="staff[0][array_obj][0][desc]" value="foobar">
```

```js
$('input').serializeJSON({useIntKeysAsArrayIndex: true});
// =>
{
  "staff": [{
    "name": "john doe",
    "another_array": [
        "something",
        "something2"
    ],
    "array_obj": [{
         "title": "something",
         "desc": "foobar"
    }]
  }]
}
```

The next staff element would have name `staff[1]`, the next `staff[2]` and so on.
