### ISSUE TITLE
Auto Number Conversion Number("10314656001009593");

### ISSUE THREAD

**Issue by mrforsythexeter** [marioizquierdo/jquery.serializeJSON#93]
These two things are not alike 

```Number("10314656001009593");```

outputs

```10314656001009592```

for the moment I will force it to a string. But I suspect it a length issue (17 numbers > 16 || > 9007199254740992)

Should have added this is with a lazy ```.serializeJSON({parseAll : true});```

**Comment by marioizquierdo** [comment]
This is a limitation of JavaScript. See this article: [Working with large intergers in JavaScript](http://2ality.com/2012/07/large-integers.html), for some examples. For example:

```js
9007199254740992 + 1
#=> 9007199254740992
```

I'm not sure what serializeJSON should do about this. Maybe add a warning in the documentation, but that won't prevent people from running into the issue.

**Comment by mrforsythexeter** [comment]
I am on my phone, so can't check how you are checking.. but maybe 

```/^[0-9]{1,15}$/```

For the test on auto? If you tested to 16 chars you would then have a harder test to perform. Failing this check you would fall back to string after this for safety?
