### ISSUE TITLE
Handling array property names with dot "."

### ISSUE THREAD

**Issue by Zilanthius** [marioizquierdo/jquery.serializeJSON#94]
input names with "." such as name[0].property are not getting serialized as an array

fixed with

```js
splitInputNameIntoKeysArray: function (nameWithNoType) {
    var keys, f;
    f = $.serializeJSON;
    keys = nameWithNoType.split('[').join('.').split('.'); // split string into array
    keys = $.map(keys, function (key) { return key.replace(/\]/g, ''); }); // remove closing brackets
    if (keys[0] === '') { keys.shift(); } // ensure no opening bracket ("[foo][inn]" should be same as "foo[inn]")
    return keys;
},
```

**Comment by marioizquierdo** [comment]
Dot notation is not supported, only brackets. The input name should be `name[0][property]`.

Changing serializeJSON to support dots would be a major update, it should include many new test cases (in spec.js) and make sure all previous tests still work as expected. I'm open to considering it, but need more evidence and support to justify a major update like that.

Thanks!

**Comment by Zilanthius** [comment]
no probs, I forked code.

the input names with dots is the name created with Microsoft MVC

e.g. @Html.TextBoxFor(x => x.Names[0].Surname) renders <input type="text" name="Names[0].Surname" />

Cheers

**Comment by Zilanthius** [comment]
This does look to common issue also fixes 

https://github.com/marioizquierdo/jquery.serializeJSON/issues/82
