### ISSUE TITLE
Disabled elements are ignored?

### ISSUE THREAD

**Issue by SheldonSir** [marioizquierdo/jquery.serializeJSON#99]
```html
<div>
        <div><span>RendingFrames</span></div>
         <input id="name" type="text" name="Info[Frames]" value="0"  disabled/>
</div>
````
After I set the input style to **disabled**, the result of jQuery.serializeJSON() will be an empty json object. Of course this is the result I want.

```html
<div disabled>
        <div><span>RendingFrames</span></div>
         <input id="name" type="text" name="Info[Frames]" value="0" />
</div>
````
If I set the style of the div to disabled, due to the inheritance relationship, its child element input style should also be disabled, but the result obtained by jquery.serializeJSON() is 
```json
"Info":{
    "Frames":"xxxx"
}
```

**Comment by SheldonSir** [comment]
Ok, this is my fault.

The [jquery.serializeArray()](https://api.jquery.com/serializeArray/) method uses the standard W3C rules for successful controls to determine which elements it should include; in particular the element cannot be disabled and must contain a name attribute.

**Comment by marioizquierdo** [comment]
You got it. The `disabled` property is not assumed to be inherited from parent elements. The input needs to have its own `disabled` property.
